version: "3.8"

services:

    data:
        container_name: sqlserver
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
            - "1433:1433"
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=yourStrongPassword12!@
        volumes:
            - sqldata:/var/opt/mssql
        networks:
            - seller-network
    
    messages:
        container_name: rabbitmq
        image: rabbitmq:3-management
        ports:
            - "15672:15672"
            - "5672:5672"
        hostname: "rabbitmq"
        environment:
            - RABBITMQ_ERLANG_COOKIE=Rand0mR4bbitMqCo0k1e
            - RABBITMQ_DEFAULT_USER=rabbitmq
            - RABBITMQ_DEFAULT_PASS=rabbitmq
        volumes:
            - rabbitmq:/var/lib/rabbitmq/mnesia
        networks: 
            - seller-network
            
    identity:
        container_name: identity
        image: plvasilev/seller-identity-service
        build:
            context: ./Server/Seller.Server
            dockerfile: ./Seller.Identity/Dockerfile
        ports: 
            - "5003:80"
        env_file: Server/Seller.Server/Seller.Shared/Common.env
        environment:
            - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=SellerIdentityDatabase;User Id=sa; Password=yourStrongPassword12!@;MultipleActiveResultSets=true
        restart: on-failure
        volumes:
            - data-protection:/root/.aspnet/DataProtection-Keys
        networks: 
            - seller-network
        depends_on:
            - data
    
    listings:
        container_name: listings
        image: plvasilev/seller-listings-service
        build:
            context: ./Server/Seller.Server
            dockerfile: ./Seller.Listings/Dockerfile
        ports: 
            - "5001:80"
        env_file: Server/Seller.Server/Seller.Shared/Common.env
        environment:
            - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=SellerListingsDatabase;User Id=sa; Password=yourStrongPassword12!@;MultipleActiveResultSets=true   
        restart: on-failure
        volumes:
            - data-protection:/root/.aspnet/DataProtection-Keys
        networks: 
            - seller-network
        depends_on:
            - data
            
    offers:
        container_name: offers
        image: plvasilev/seller-offers-service
        build:
            context: ./Server/Seller.Server
            dockerfile: ./Seller.Offers/Dockerfile
        ports: 
            - "5005:80"
        env_file: Server/Seller.Server/Seller.Shared/Common.env
        environment:
            - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=SellerOffersDatabase;User Id=sa; Password=yourStrongPassword12!@;MultipleActiveResultSets=true       
        restart: on-failure
        volumes:
            - data-protection:/root/.aspnet/DataProtection-Keys
        networks: 
            - seller-network
        depends_on:
            - data 

    contactus:
        container_name: contactus
        image: plvasilev/seller-contactus-service
        build:
            context: ./Server/Seller.Server
            dockerfile: ./Seller.Messages/Dockerfile
        ports: 
            - "5007:80"
        env_file: Server/Seller.Server/Seller.Shared/Common.env
        environment:
            - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=SellerMessagesDatabase;User Id=sa; Password=yourStrongPassword12!@;MultipleActiveResultSets=true
        restart: on-failure
        volumes:
            - data-protection:/root/.aspnet/DataProtection-Keys
        networks: 
            - seller-network
        depends_on:
            - data 

    notifications:
        container_name: notifications
        image: plvasilev/seller-notifications-service
        build:
            context: ./Server/Seller.Server
            dockerfile: ./Seller.Notifications/Dockerfile
        ports: 
            - "5011:80"
        env_file: Server/Seller.Server/Seller.Shared/Common.env
        environment:
            - NotificationSettings__AllowedOrigins=http://localhost
        restart: on-failure
        volumes:
            - data-protection:/root/.aspnet/DataProtection-Keys
        networks: 
            - seller-network
        depends_on:
            - data   

    lisinggateway:
        container_name: lisinggateway
        image: plvasilev/seller-gateway-service
        build:
            context: ./Server/Seller.Server
            dockerfile: ./Seller.Listing.Gateway/Dockerfile
        ports: 
            - "5009:80"
        env_file: Server/Seller.Server/Seller.Shared/Common.env
        restart: on-failure
        volumes:
            - data-protection:/root/.aspnet/DataProtection-Keys
        networks: 
            - seller-network
        depends_on:
            - data 

    administration:
        container_name: administration
        image: plvasilev/seller-administration-service
        build:
            context: ./Server/Seller.Server
            dockerfile: ./Seller.Admin/Dockerfile
        ports: 
            - "5013:80"
        env_file: Server/Seller.Server/Seller.Shared/Common.env
        environment:
            - ServiceEndpoints__Identity=http://identity
            - ServiceEndpoints__Message=http://contactus
        restart: on-failure
        volumes:
            - data-protection:/root/.aspnet/DataProtection-Keys
        networks: 
            - seller-network
        depends_on:
            - data    

    watchdog:
        container_name: watchdog
        image: plvasilev/seller-watchdog-service
        build:
            context: ./Server/Seller.Server
            dockerfile: ./Seller.Watchdog/Dockerfile
        ports: 
            - "5015:80"
        env_file: Server/Seller.Server/Seller.Shared/Common.env
        environment:
            - HealthChecks-UI__HealthChecks__0__Name=Listings
            - HealthChecks-UI__HealthChecks__0__Uri=http://Listings/health
            - HealthChecks-UI__HealthChecks__1__Name=Identity
            - HealthChecks-UI__HealthChecks__1__Uri=http://Identity/health
            - HealthChecks-UI__HealthChecks__2__Name=Offers
            - HealthChecks-UI__HealthChecks__2__Uri=http://Offers/health
        restart: on-failure
        volumes:
            - data-protection:/root/.aspnet/DataProtection-Keys
        networks: 
            - seller-network
        depends_on:
            - data
            
    angular:
        container_name: angular
        image: plvasilev/seller-client-service
        build:
             context: ./Client/Seller.Client
             dockerfile: ./Dockerfile
        ports:
            - "80:80"          
        restart: on-failure 
        networks: 
            - seller-network        
        
networks:
    seller-network:
    
volumes:
    sqldata:
    rabbitmq:
    data-protection: