apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: administration-client-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi

---

apiVersion: v1
kind: Service
metadata:
  name: administration-client
spec:
  type: LoadBalancer
  ports:
  - port: 5013
    targetPort: 80
  selector:
    web-client: administration-client

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: administration-client
spec:
  selector:
    matchLabels:
      web-client: administration-client
  template:
    metadata:
      labels:
        web-client: administration-client
        system: client
    spec:
      containers:
      - name: administration-client
        image: plvasilev/seller-administration-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "512Mi"
            cpu: "250m"
        env:
        - name: AppSettings__Secret
          valueFrom:
            secretKeyRef:
              name: environment-secrets
              key: security-token-secret
        - name: ServiceEndpoints__Identity
          valueFrom:
            configMapKeyRef:
              name: environment-settings
              key: administration-identity-endpoint
        - name: ServiceEndpoints__Message
          valueFrom:
            configMapKeyRef:
              name: environment-settings
              key: administration-contactus-endpoint
        volumeMounts:
        - name: administration-client-data
          mountPath: /root/.aspnet/DataProtection-Keys
      volumes:
      - name: administration-client-data
        persistentVolumeClaim:
          claimName: administration-client-data
