apiVersion: v1
kind: Service
metadata:
  name: watchdog-client
spec:
  type: LoadBalancer
  ports:
  - port: 5015
    targetPort: 80
  selector:
    web-client: watchdog-client

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: watchdog-client
spec:
  selector:
    matchLabels:
      web-client: watchdog-client
  template:
    metadata:
      labels:
        web-client: watchdog-client
        system: client
    spec:
      containers:
      - name: watchdog-client
        image: plvasilev/seller-watchdog-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "512Mi"
            cpu: "250m"
        env:
        - name: HealthChecks-UI__HealthChecks__0__Name
          value: Listings
        - name: HealthChecks-UI__HealthChecks__0__Uri
          valueFrom:
            configMapKeyRef:
              name: environment-settings
              key: watchdog-listings-health
        - name: HealthChecks-UI__HealthChecks__1__Name
          value: Identity
        - name: HealthChecks-UI__HealthChecks__1__Uri
          valueFrom:
            configMapKeyRef:
              name: environment-settings
              key: watchdog-identity-health
        - name: HealthChecks-UI__HealthChecks__2__Name
          value: Offers
        - name: HealthChecks-UI__HealthChecks__2__Uri
          valueFrom:
            configMapKeyRef:
              name: environment-settings
              key: watchdog-offers-health
